# Generated by Django 2.0.2 on 2020-02-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank='true', max_length=200)),
                ('quantity', models.CharField(blank='true', max_length=200)),
                ('price', models.CharField(blank='true', max_length=200)),
            ],
        ),
    ]
